# Generated by Django 4.2.28 on 2026-03-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kb_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('general', 'General'), ('domain', 'Domain'), ('private', 'Private')], default='general', max_length=20)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('error', 'Error'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('file_count', models.IntegerField(default=0)),
                ('vector_store', models.JSONField(blank=True, default=dict)),
                ('pipeline', models.JSONField(blank=True, default=dict)),
                ('knowledge_graph', models.JSONField(blank=True, default=dict)),
                ('mcp', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knowledge_bases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('size', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='knowledgebase.knowledgebase')),
            ],
            options={
                'db_table': 'kb_documents',
                'unique_together': {('knowledge_base', 'document_id')},
            },
        ),
    ]
