from django.db import migrations, models


def seed_hub_data(apps, schema_editor):
    DatasetRepo = apps.get_model('hub', 'DatasetRepo')
    DatasetVersion = apps.get_model('hub', 'DatasetVersion')
    DatasetFile = apps.get_model('hub', 'DatasetFile')
    ModelRepo = apps.get_model('hub', 'ModelRepo')
    ModelVersion = apps.get_model('hub', 'ModelVersion')
    ModelFile = apps.get_model('hub', 'ModelFile')

    dataset_specs = [
        {
            'repo_id': 'OpenDCAI/autodrive-raw-nuscenes',
            'namespace': 'OpenDCAI',
            'slug': 'autodrive-raw-nuscenes',
            'author': 'motional-labs',
            'name': 'AutoDrive Raw - nuScenes',
            'task': 'object-detection',
            'domain': 'autonomous-driving',
            'modality': 'multimodal',
            'language': 'en',
            'license': 'cc-by-nc-sa-4.0',
            'description': 'Multimodal autonomous driving corpus with camera, lidar, radar, GPS and IMU streams.',
            'summary': 'HF-style dataset repository with structured metadata, revisions, files, and preview rows.',
            'downloads': 2100000,
            'likes': 4200,
            'row_count': 1400000,
            'size_label': '680GB',
            'dataset_type': 'original',
            'readonly': False,
            'tags': ['autonomous-driving', 'multimodal', 'lidar', 'camera'],
            'metadata': {
                'splits': ['train', 'validation'],
                'formats': ['parquet', 'jsonl'],
                'sensors': ['camera', 'lidar', 'radar', 'gps', 'imu'],
                'conditions': ['day', 'night', 'rain', 'clear'],
            },
            'card_sections': [
                {'title': 'Dataset Description', 'content': 'High-resolution driving scenes with synchronized multi-sensor observations for perception and planning.'},
                {'title': 'Repository Layout', 'content': 'Each revision exposes parquet manifests, metadata JSON, and sample preview files.'},
                {'title': 'HF Compatibility', 'content': 'The repository is modeled after a Hugging Face dataset repo with card metadata, revisions, and file previews.'},
            ],
            'derived_repo_ids': ['OpenDCAI/autodrive-derived-nuscenes-filtered'],
            'versions': [
                {
                    'revision': 'main',
                    'commit_sha': '5b310d0',
                    'row_count': 1400000,
                    'size_label': '680GB',
                    'is_latest': True,
                    'manifest': {'splits': {'train': 1200000, 'validation': 200000}},
                    'files': [
                        {
                            'path': 'README.md',
                            'file_type': 'markdown',
                            'size_bytes': 4096,
                            'size_label': '4KB',
                            'preview_text': '# AutoDrive Raw - nuScenes\n\nRepository card for the nuScenes raw dataset.',
                            'sha256': 'sha256:dataset-readme',
                        },
                        {
                            'path': 'train/metadata.parquet',
                            'file_type': 'parquet',
                            'size_bytes': 268435456,
                            'size_label': '256MB',
                            'split': 'train',
                            'row_count': 1200000,
                            'preview_rows': [
                                {'scene_id': 'scene-001', 'timestamp': '2025-02-01T08:00:00Z', 'weather': 'clear', 'sensor_count': 13},
                                {'scene_id': 'scene-002', 'timestamp': '2025-02-01T08:00:10Z', 'weather': 'rain', 'sensor_count': 13},
                            ],
                            'sha256': 'sha256:nuscenes-train',
                        },
                        {
                            'path': 'validation/samples.jsonl',
                            'file_type': 'jsonl',
                            'size_bytes': 1048576,
                            'size_label': '1MB',
                            'split': 'validation',
                            'row_count': 200000,
                            'preview_rows': [
                                {'image': 'samples/0001.jpg', 'lidar': 'sweeps/0001.bin', 'objects': ['car', 'pedestrian']},
                                {'image': 'samples/0002.jpg', 'lidar': 'sweeps/0002.bin', 'objects': ['truck', 'bicycle']},
                            ],
                            'sha256': 'sha256:nuscenes-val',
                        },
                    ],
                },
                {
                    'revision': 'refs/pr/12',
                    'commit_sha': '19a731b',
                    'row_count': 1385000,
                    'size_label': '672GB',
                    'is_latest': False,
                    'manifest': {'note': 'pre-cleaned revision'},
                    'files': [],
                },
            ],
        },
        {
            'repo_id': 'OpenDCAI/autodrive-derived-nuscenes-filtered',
            'namespace': 'OpenDCAI',
            'slug': 'autodrive-derived-nuscenes-filtered',
            'author': 'autodrive-ai',
            'name': 'AutoDrive Derived - nuScenes Filtered',
            'task': 'object-detection',
            'domain': 'autonomous-driving',
            'modality': 'multimodal',
            'language': 'en',
            'license': 'apache-2.0',
            'description': 'Quality-filtered derivative of nuScenes for downstream training and evaluation.',
            'summary': 'Derived read-only dataset with explicit parent linkage and preview artifacts.',
            'downloads': 980000,
            'likes': 2150,
            'row_count': 910000,
            'size_label': '214GB',
            'dataset_type': 'derived',
            'readonly': True,
            'parent_repo_id': 'OpenDCAI/autodrive-raw-nuscenes',
            'tags': ['autonomous-driving', 'derived', 'filtered'],
            'metadata': {
                'pipeline': 'DataFlow-MM/filter-quality',
                'splits': ['train', 'validation'],
                'formats': ['parquet'],
            },
            'card_sections': [
                {'title': 'Dataset Description', 'content': 'Read-only processed dataset generated from the raw nuScenes repository through a quality filter pipeline.'},
                {'title': 'Lineage', 'content': 'Includes parent repo reference, pipeline metadata, and derived revision history.'},
            ],
            'versions': [
                {
                    'revision': 'main',
                    'commit_sha': '8c71fe2',
                    'row_count': 910000,
                    'size_label': '214GB',
                    'is_latest': True,
                    'manifest': {'pipeline': 'DataFlow-MM/filter-quality'},
                    'files': [
                        {
                            'path': 'README.md',
                            'file_type': 'markdown',
                            'size_bytes': 2048,
                            'size_label': '2KB',
                            'preview_text': '# AutoDrive Derived - nuScenes Filtered\n\nFiltered sample repository card.',
                            'sha256': 'sha256:filtered-readme',
                        },
                        {
                            'path': 'train/filtered.parquet',
                            'file_type': 'parquet',
                            'size_bytes': 134217728,
                            'size_label': '128MB',
                            'split': 'train',
                            'row_count': 800000,
                            'preview_rows': [
                                {'scene_id': 'scene-101', 'quality_score': 0.98, 'kept': True},
                                {'scene_id': 'scene-102', 'quality_score': 0.96, 'kept': True},
                            ],
                            'sha256': 'sha256:filtered-train',
                        },
                    ],
                },
            ],
        },
        {
            'repo_id': 'OpenDCAI/math-olympiad-problems',
            'namespace': 'OpenDCAI',
            'slug': 'math-olympiad-problems',
            'author': 'deepmind',
            'name': 'Math Olympiad Problems',
            'task': 'question-answering',
            'domain': 'mathematics',
            'modality': 'text',
            'language': 'en',
            'license': 'cc-by-4.0',
            'description': 'Competition-grade math problems with structured solutions and annotations.',
            'summary': 'Text dataset repository with JSONL previews and dataset card metadata.',
            'downloads': 4800000,
            'likes': 3600,
            'row_count': 125000,
            'size_label': '280MB',
            'tags': ['math', 'qa', 'olympiad'],
            'metadata': {'splits': ['train', 'test'], 'formats': ['jsonl']},
            'card_sections': [
                {'title': 'Dataset Description', 'content': 'Curated olympiad problems across algebra, geometry, combinatorics, and number theory.'},
                {'title': 'Training Use', 'content': 'Can be loaded as SFT data or as evaluation prompts for reasoning models.'},
            ],
            'versions': [
                {
                    'revision': 'main',
                    'commit_sha': 'a1b2c3d',
                    'row_count': 125000,
                    'size_label': '280MB',
                    'is_latest': True,
                    'manifest': {'splits': {'train': 100000, 'test': 25000}},
                    'files': [
                        {
                            'path': 'README.md',
                            'file_type': 'markdown',
                            'size_bytes': 1800,
                            'size_label': '2KB',
                            'preview_text': '# Math Olympiad Problems\n\nReasoning dataset card.',
                            'sha256': 'sha256:math-readme',
                        },
                        {
                            'path': 'train.jsonl',
                            'file_type': 'jsonl',
                            'size_bytes': 7340032,
                            'size_label': '7MB',
                            'split': 'train',
                            'row_count': 100000,
                            'preview_rows': [
                                {'problem': 'Let a,b,c be positive integers...', 'answer': 'Using AM-GM, we derive...'},
                                {'problem': 'Prove that every finite group...', 'answer': 'Apply the class equation...'},
                            ],
                            'sha256': 'sha256:math-train',
                        },
                    ],
                },
            ],
        },
    ]

    model_specs = [
        {
            'repo_id': 'Qwen/Qwen3-8B',
            'namespace': 'Qwen',
            'slug': 'Qwen3-8B',
            'author': 'Qwen',
            'name': 'Qwen3-8B',
            'pipeline_tag': 'text-generation',
            'library': 'transformers',
            'language': 'multilingual',
            'license': 'apache-2.0',
            'description': 'General-purpose 8B language model exposed as a real hub repo with versions, files, and card metadata.',
            'summary': 'Base foundation model entry for the new model hub.',
            'downloads': 3500000,
            'likes': 12000,
            'featured': True,
            'tags': ['transformers', 'pytorch', 'qwen'],
            'metrics': [
                {'name': 'MMLU', 'value': '74.1'},
                {'name': 'GSM8K', 'value': '82.3'},
            ],
            'card_sections': [
                {'title': 'Model Description', 'content': 'A multilingual causal LM suitable for instruction-following, coding, and general NLP tasks.'},
                {'title': 'Repository Layout', 'content': 'Includes config, tokenizer, safetensors weights, and generation config.'},
                {'title': 'Use Cases', 'content': 'Chat, agent orchestration, dataset labeling, and synthetic data generation.'},
            ],
            'versions': [
                {
                    'revision': 'main',
                    'commit_sha': '0f31a9e',
                    'framework': 'transformers',
                    'params_label': '8B',
                    'quantization': '',
                    'is_latest': True,
                    'files': [
                        {
                            'path': 'README.md',
                            'file_type': 'markdown',
                            'size_bytes': 2048,
                            'size_label': '2KB',
                            'preview_text': '# Qwen3-8B\n\nModel card for Qwen3-8B.',
                            'sha256': 'sha256:qwen-readme',
                        },
                        {
                            'path': 'config.json',
                            'file_type': 'json',
                            'size_bytes': 1200,
                            'size_label': '1KB',
                            'preview_text': '{"architectures":["QwenForCausalLM"],"hidden_size":4096,"num_attention_heads":32}',
                            'sha256': 'sha256:qwen-config',
                        },
                        {
                            'path': 'model-00001-of-00002.safetensors',
                            'file_type': 'weights',
                            'size_bytes': 4294967296,
                            'size_label': '4GB',
                            'sha256': 'sha256:qwen-weight-1',
                        },
                    ],
                },
                {
                    'revision': 'v1.0.1',
                    'commit_sha': '9bb71af',
                    'framework': 'transformers',
                    'params_label': '8B',
                    'quantization': 'int4',
                    'is_latest': False,
                    'files': [],
                },
            ],
        },
        {
            'repo_id': 'OpenDCAI/Qwen3-14B-Med-SFT',
            'namespace': 'OpenDCAI',
            'slug': 'Qwen3-14B-Med-SFT',
            'author': 'OpenDCAI',
            'name': 'Qwen3-14B-Med-SFT',
            'pipeline_tag': 'text-generation',
            'library': 'transformers',
            'language': 'multilingual',
            'license': 'apache-2.0',
            'description': 'Medical-domain fine-tuned variant with explicit lineage to base model and training dataset.',
            'summary': 'Domain model card entry for the new model hub.',
            'downloads': 450000,
            'likes': 3200,
            'base_model': 'Qwen/Qwen3-8B',
            'dataset': 'OpenDCAI/math-olympiad-problems',
            'tags': ['transformers', 'pytorch', 'medical', 'sft'],
            'metrics': [
                {'name': 'MedQA', 'value': '72.8'},
                {'name': 'PubMedQA', 'value': '79.4'},
            ],
            'card_sections': [
                {'title': 'Model Description', 'content': 'Supervised fine-tuned model specialized for medical QA and clinical reasoning.'},
                {'title': 'Training Data', 'content': 'Built from curated instruction-response pairs and domain reasoning datasets.'},
            ],
            'versions': [
                {
                    'revision': 'main',
                    'commit_sha': '2ab4c6d',
                    'framework': 'transformers',
                    'params_label': '14B',
                    'quantization': '',
                    'is_latest': True,
                    'files': [
                        {
                            'path': 'README.md',
                            'file_type': 'markdown',
                            'size_bytes': 2200,
                            'size_label': '2KB',
                            'preview_text': '# Qwen3-14B-Med-SFT\n\nModel card for the medical SFT variant.',
                            'sha256': 'sha256:med-readme',
                        },
                        {
                            'path': 'adapter_config.json',
                            'file_type': 'json',
                            'size_bytes': 900,
                            'size_label': '1KB',
                            'preview_text': '{"r":64,"lora_alpha":16,"target_modules":["q_proj","v_proj"]}',
                            'sha256': 'sha256:med-adapter',
                        },
                    ],
                },
            ],
        },
        {
            'repo_id': 'sentence-transformers/all-MiniLM-L6-v2',
            'namespace': 'sentence-transformers',
            'slug': 'all-MiniLM-L6-v2',
            'author': 'sentence-transformers',
            'name': 'all-MiniLM-L6-v2',
            'pipeline_tag': 'feature-extraction',
            'library': 'transformers',
            'language': 'en',
            'license': 'apache-2.0',
            'description': 'Embedding model entry with repo files and usage snippets for vector retrieval.',
            'summary': 'Embedding model for retrieval, ranking, and semantic search.',
            'downloads': 5600000,
            'likes': 7200,
            'featured': True,
            'tags': ['transformers', 'sentence-transformers', 'embedding'],
            'metrics': [{'name': 'MTEB', 'value': '61.5'}],
            'card_sections': [
                {'title': 'Model Description', 'content': 'Maps sentences and short documents to dense vectors for semantic retrieval.'},
                {'title': 'Usage', 'content': 'Suitable for retrieval, RAG indexing, and reranking pipelines.'},
            ],
            'versions': [
                {
                    'revision': 'main',
                    'commit_sha': '76abc44',
                    'framework': 'transformers',
                    'params_label': '22M',
                    'quantization': '',
                    'is_latest': True,
                    'files': [
                        {
                            'path': 'README.md',
                            'file_type': 'markdown',
                            'size_bytes': 1600,
                            'size_label': '2KB',
                            'preview_text': '# all-MiniLM-L6-v2\n\nEmbedding model card.',
                            'sha256': 'sha256:embed-readme',
                        },
                        {
                            'path': 'modules.json',
                            'file_type': 'json',
                            'size_bytes': 700,
                            'size_label': '1KB',
                            'preview_text': '{"modules":["0_Transformer","1_Pooling","2_Normalize"]}',
                            'sha256': 'sha256:embed-modules',
                        },
                    ],
                },
            ],
        },
    ]

    for dataset_spec in dataset_specs:
        versions = dataset_spec.pop('versions')
        repo = DatasetRepo.objects.create(**dataset_spec)
        for version_index, version_spec in enumerate(versions):
            files = version_spec.pop('files')
            version = DatasetVersion.objects.create(repo=repo, **version_spec)
            for file_index, file_spec in enumerate(files):
                DatasetFile.objects.create(version=version, sort_order=file_index, **file_spec)

    for model_spec in model_specs:
        versions = model_spec.pop('versions')
        repo = ModelRepo.objects.create(**model_spec)
        for version_index, version_spec in enumerate(versions):
            files = version_spec.pop('files')
            version = ModelVersion.objects.create(repo=repo, **version_spec)
            for file_index, file_spec in enumerate(files):
                ModelFile.objects.create(version=version, sort_order=file_index, **file_spec)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='DatasetRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_id', models.CharField(max_length=255, unique=True)),
                ('namespace', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=120)),
                ('domain', models.CharField(max_length=120)),
                ('modality', models.CharField(max_length=120)),
                ('language', models.CharField(default='en', max_length=64)),
                ('license', models.CharField(default='apache-2.0', max_length=120)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('dataset_type', models.CharField(blank=True, default='', max_length=32)),
                ('readonly', models.BooleanField(default=False)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('size_label', models.CharField(default='0B', max_length=64)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('card_sections', models.JSONField(blank=True, default=list)),
                ('parent_repo_id', models.CharField(blank=True, default='', max_length=255)),
                ('derived_repo_ids', models.JSONField(blank=True, default=list)),
                ('hf_compatible', models.BooleanField(default=True)),
            ],
            options={'ordering': ['repo_id']},
        ),
        migrations.CreateModel(
            name='ModelRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repo_id', models.CharField(max_length=255, unique=True)),
                ('namespace', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('pipeline_tag', models.CharField(max_length=120)),
                ('library', models.CharField(default='transformers', max_length=120)),
                ('language', models.CharField(default='en', max_length=64)),
                ('license', models.CharField(default='apache-2.0', max_length=120)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, default='')),
                ('visibility', models.CharField(default='public', max_length=32)),
                ('downloads', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('base_model', models.CharField(blank=True, default='', max_length=255)),
                ('dataset', models.CharField(blank=True, default='', max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('card_sections', models.JSONField(blank=True, default=list)),
                ('hf_compatible', models.BooleanField(default=True)),
            ],
            options={'ordering': ['repo_id']},
        ),
        migrations.CreateModel(
            name='DatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.CharField(max_length=120)),
                ('commit_sha', models.CharField(max_length=64)),
                ('manifest', models.JSONField(blank=True, default=dict)),
                ('row_count', models.PositiveBigIntegerField(default=0)),
                ('size_label', models.CharField(default='0B', max_length=64)),
                ('is_latest', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='versions', to='hub.datasetrepo')),
            ],
            options={'ordering': ['-created_at', '-id'], 'unique_together': {('repo', 'revision')}},
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.CharField(max_length=120)),
                ('commit_sha', models.CharField(max_length=64)),
                ('framework', models.CharField(default='transformers', max_length=120)),
                ('params_label', models.CharField(blank=True, default='', max_length=64)),
                ('quantization', models.CharField(blank=True, default='', max_length=64)),
                ('is_latest', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='versions', to='hub.modelrepo')),
            ],
            options={'ordering': ['-created_at', '-id'], 'unique_together': {('repo', 'revision')}},
        ),
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('size_label', models.CharField(default='0B', max_length=64)),
                ('split', models.CharField(blank=True, default='', max_length=64)),
                ('row_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('preview_text', models.TextField(blank=True, default='')),
                ('sha256', models.CharField(blank=True, default='', max_length=128)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='files', to='hub.datasetversion')),
            ],
            options={'ordering': ['sort_order', 'path'], 'unique_together': {('version', 'path')}},
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(max_length=512)),
                ('file_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('size_label', models.CharField(default='0B', max_length=64)),
                ('sha256', models.CharField(blank=True, default='', max_length=128)),
                ('preview_text', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='files', to='hub.modelversion')),
            ],
            options={'ordering': ['sort_order', 'path'], 'unique_together': {('version', 'path')}},
        ),
        migrations.RunPython(seed_hub_data, migrations.RunPython.noop),
    ]
