# Generated by Django 4.2.29 on 2026-03-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_knowledge_hub'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetrepo',
            name='default_revision',
            field=models.CharField(default='main', max_length=120),
        ),
        migrations.AddField(
            model_name='datasetrepo',
            name='provider_bindings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasetrepo',
            name='sync_status',
            field=models.CharField(default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='artifact_uri',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='provider_commit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='datasetversion',
            name='provider_revision',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgebuild',
            name='provider_job_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgebuild',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgebuild',
            name='provider_status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='knowledgerepo',
            name='default_revision',
            field=models.CharField(default='main', max_length=120),
        ),
        migrations.AddField(
            model_name='knowledgerepo',
            name='provider_bindings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgerepo',
            name='sync_status',
            field=models.CharField(default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='artifact_uri',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='provider_commit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='knowledgeversion',
            name='provider_revision',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelrepo',
            name='default_revision',
            field=models.CharField(default='main', max_length=120),
        ),
        migrations.AddField(
            model_name='modelrepo',
            name='provider_bindings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelrepo',
            name='sync_status',
            field=models.CharField(default='local', max_length=32),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='artifact_uri',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='provider_commit',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='provider_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='provider_revision',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
