# Generated by Django 4.2.28 on 2026-03-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DFConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Untitled Conversation', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Conversation configuration')),
                ('total_messages', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='df_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DataFlow Conversation',
                'verbose_name_plural': 'DataFlow Conversations',
                'db_table': 'df_conversation',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DFMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=20)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='df_conversation.dfconversation')),
            ],
            options={
                'verbose_name': 'DataFlow Message',
                'verbose_name_plural': 'DataFlow Messages',
                'db_table': 'df_message',
                'ordering': ['created_at'],
            },
        ),
    ]
