# Generated by Django 4.2.28 on 2026-03-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('subscribers_count', models.IntegerField(default=0)),
                ('tools', models.JSONField(blank=True, default=list)),
                ('collection_and_kbs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tool_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('openapi_json_path', models.TextField(blank=True, null=True)),
                ('endpoints', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_tools', to='agent.agent')),
            ],
            options={
                'db_table': 'agent_tools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='agent.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_subscriptions',
                'unique_together': {('user', 'agent')},
            },
        ),
    ]
