from django.urls import path

from . import api


urlpatterns = [
    path('integrations/gitea/webhook', api.gitea_webhook_v2, name='hub-gitea-webhook-v2'),
    path('datasets', api.dataset_list_v2, name='hub-dataset-list-v2'),
    path('datasets/<path:repo_id>/revisions', api.dataset_revisions_v2, name='hub-dataset-revisions-v2'),
    path('datasets/<path:repo_id>/sync', api.dataset_sync_v2, name='hub-dataset-sync-v2'),
    path('datasets/<path:repo_id>/tree', api.dataset_tree_v2, name='hub-dataset-tree-v2'),
    path('datasets/<path:repo_id>/splits', api.dataset_splits_v2, name='hub-dataset-splits-v2'),
    path('datasets/<path:repo_id>/rows', api.dataset_rows_v2, name='hub-dataset-rows-v2'),
    path('datasets/<path:repo_id>/preview', api.dataset_preview_v2, name='hub-dataset-preview-v2'),
    path('datasets/<path:repo_id>/resolve/<str:revision>/<path:file_path>', api.dataset_resolve_v2, name='hub-dataset-resolve-v2'),
    path('datasets/<path:repo_id>', api.dataset_detail_v2, name='hub-dataset-detail-v2'),
    path('models', api.model_list_v2, name='hub-model-list-v2'),
    path('models/<path:repo_id>/revisions', api.model_revisions_v2, name='hub-model-revisions-v2'),
    path('models/<path:repo_id>/sync', api.model_sync_v2, name='hub-model-sync-v2'),
    path('models/<path:repo_id>/tree', api.model_tree_v2, name='hub-model-tree-v2'),
    path('models/<path:repo_id>/preview', api.model_preview_v2, name='hub-model-preview-v2'),
    path('models/<path:repo_id>/resolve/<str:revision>/<path:file_path>', api.model_resolve_v2, name='hub-model-resolve-v2'),
    path('models/<path:repo_id>', api.model_detail_v2, name='hub-model-detail-v2'),
    path('knowledge-bases', api.knowledge_list_v2, name='hub-knowledge-list-v2'),
    path('knowledge-bases/<path:repo_id>/revisions', api.knowledge_revisions_v2, name='hub-knowledge-revisions-v2'),
    path('knowledge-bases/<path:repo_id>/sync', api.knowledge_sync_v2, name='hub-knowledge-sync-v2'),
    path('knowledge-bases/<path:repo_id>/tree', api.knowledge_tree_v2, name='hub-knowledge-tree-v2'),
    path('knowledge-bases/<path:repo_id>/rows', api.knowledge_rows_v2, name='hub-knowledge-rows-v2'),
    path('knowledge-bases/<path:repo_id>/preview', api.knowledge_preview_v2, name='hub-knowledge-preview-v2'),
    path('knowledge-bases/<path:repo_id>/builds', api.knowledge_builds_v2, name='hub-knowledge-builds-v2'),
    path('knowledge-bases/<path:repo_id>/resolve/<str:revision>/<path:file_path>', api.knowledge_resolve_v2, name='hub-knowledge-resolve-v2'),
    path('knowledge-bases/<path:repo_id>', api.knowledge_detail_v2, name='hub-knowledge-detail-v2'),
    path('hf/api/datasets', api.hf_list_datasets, name='hf-list-datasets'),
    path('hf/api/datasets/<path:repo_id>/tree/<str:revision>', api.hf_dataset_tree, name='hf-dataset-tree'),
    path('hf/api/datasets/<path:repo_id>/paths-info/<str:revision>', api.hf_dataset_paths_info, name='hf-dataset-paths-info'),
    path('hf/api/datasets/<path:repo_id>/commits/<str:revision>', api.hf_dataset_commits, name='hf-dataset-commits'),
    path('hf/api/datasets/<path:repo_id>', api.hf_dataset_metadata, name='hf-dataset-metadata'),
    path('hf/api/models', api.hf_list_models, name='hf-list-models'),
    path('hf/api/models/<path:repo_id>', api.hf_model_metadata, name='hf-model-metadata'),
    path('hf/is-valid', api.hf_is_valid, name='hf-is-valid'),
    path('hf/viewer/is-valid', api.hf_is_valid, name='hf-viewer-is-valid'),
    path('hf/splits', api.hf_get_splits, name='hf-get-splits'),
    path('hf/viewer/splits', api.hf_get_splits, name='hf-viewer-get-splits'),
    path('hf/rows', api.hf_get_rows, name='hf-get-rows'),
    path('hf/viewer/rows', api.hf_get_rows, name='hf-viewer-get-rows'),
    path('hf/first-rows', api.hf_get_rows, name='hf-first-rows'),
    path('hf/viewer/first-rows', api.hf_get_rows, name='hf-viewer-first-rows'),
    path('hf/info', api.hf_dataset_info, name='hf-dataset-info'),
    path('hf/viewer/info', api.hf_dataset_info, name='hf-viewer-dataset-info'),
    path('hf/parquet', api.hf_parquet_list, name='hf-parquet-list'),
    path('hf/viewer/parquet', api.hf_parquet_list, name='hf-viewer-parquet-list'),
    path('hf/datasets/<path:repo_id>/resolve/<str:revision>/<path:file_path>', api.hf_resolve_file, name='hf-resolve-file'),
    path('hf/models/<path:repo_id>/resolve/<str:revision>/<path:file_path>', api.hf_model_resolve_file, name='hf-model-resolve-file'),
]
