create table django_content_type
(
    id        integer generated by default as identity
        primary key,
    app_label varchar(100) not null,
    model     varchar(100) not null,
    constraint django_content_type_app_label_model_76bd3d3b_uniq
        unique (app_label, model)
);

alter table django_content_type
    owner to myscale_kb_backend;

INSERT INTO public.django_content_type (app_label, model) VALUES ('admin', 'logentry');
INSERT INTO public.django_content_type (app_label, model) VALUES ('auth', 'permission');
INSERT INTO public.django_content_type (app_label, model) VALUES ('auth', 'group');
INSERT INTO public.django_content_type (app_label, model) VALUES ('contenttypes', 'contenttype');
INSERT INTO public.django_content_type (app_label, model) VALUES ('sessions', 'session');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_results', 'taskresult');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_results', 'chordcounter');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_results', 'groupresult');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_beat', 'crontabschedule');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_beat', 'intervalschedule');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_beat', 'periodictask');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_beat', 'periodictasks');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_beat', 'solarschedule');
INSERT INTO public.django_content_type (app_label, model) VALUES ('django_celery_beat', 'clockedschedule');
INSERT INTO public.django_content_type (app_label, model) VALUES ('user', 'myuser');
INSERT INTO public.django_content_type (app_label, model) VALUES ('agent', 'agent');
INSERT INTO public.django_content_type (app_label, model) VALUES ('agent', 'agentcollection');
INSERT INTO public.django_content_type (app_label, model) VALUES ('agent', 'agentsubscribe');
INSERT INTO public.django_content_type (app_label, model) VALUES ('agent', 'agenttools');
INSERT INTO public.django_content_type (app_label, model) VALUES ('document', 'document');
INSERT INTO public.django_content_type (app_label, model) VALUES ('collection', 'collection');
INSERT INTO public.django_content_type (app_label, model) VALUES ('collection', 'collectiondocument');
INSERT INTO public.django_content_type (app_label, model) VALUES ('knowledgebase', 'knowledgebase');
INSERT INTO public.django_content_type (app_label, model) VALUES ('chat', 'conversation');
INSERT INTO public.django_content_type (app_label, model) VALUES ('chat', 'question');
INSERT INTO public.django_content_type (app_label, model) VALUES ('chat', 'conversationshare');
INSERT INTO public.django_content_type (app_label, model) VALUES ('customadmin', 'globalconfig');
INSERT INTO public.django_content_type (app_label, model) VALUES ('openapi', 'openapikey');
INSERT INTO public.django_content_type (app_label, model) VALUES ('openapi', 'openapilog');
INSERT INTO public.django_content_type (app_label, model) VALUES ('openapi', 'openapiusage');
INSERT INTO public.django_content_type (app_label, model) VALUES ('dataset', 'dataset');
INSERT INTO public.django_content_type (app_label, model) VALUES ('dataset', 'file');
INSERT INTO public.django_content_type (app_label, model) VALUES ('task', 'task');
INSERT INTO public.django_content_type (app_label, model) VALUES ('dataset', 'datasetfile');
INSERT INTO public.django_content_type (app_label, model) VALUES ('user', 'emailverificationcode');
INSERT INTO public.django_content_type (app_label, model) VALUES ('pipeline_config', 'pipelineconfig');
INSERT INTO public.django_content_type (app_label, model) VALUES ('template', 'template');
INSERT INTO public.django_content_type (app_label, model) VALUES ('user', 'apikeypool');
INSERT INTO public.django_content_type (app_label, model) VALUES ('organization', 'organization');
INSERT INTO public.django_content_type (app_label, model) VALUES ('openapi', 'asyncuploadtask');
INSERT INTO public.django_content_type (app_label, model) VALUES ('user', 'invitecode');
INSERT INTO public.django_content_type (app_label, model) VALUES ('openapi', 'adapterexternaltask');
INSERT INTO public.django_content_type (app_label, model) VALUES ('openapi', 'adapterinternaltaskmapping');
INSERT INTO public.django_content_type (app_label, model) VALUES ('df_conversation', 'conversation');
INSERT INTO public.django_content_type (app_label, model) VALUES ('third_party', 'kpscallback');
