create table django_celery_beat_clockedschedule
(
    id           integer generated by default as identity
        primary key,
    clocked_time timestamp with time zone not null
);

alter table django_celery_beat_clockedschedule
    owner to myscale_kb_backend;

