create table django_celery_beat_periodictask
(
    id              integer generated by default as identity
        primary key,
    name            varchar(200)             not null
        unique,
    task            varchar(200)             not null,
    args            text                     not null,
    kwargs          text                     not null,
    queue           varchar(200),
    exchange        varchar(200),
    routing_key     varchar(200),
    expires         timestamp with time zone,
    enabled         boolean                  not null,
    last_run_at     timestamp with time zone,
    total_run_count integer                  not null
        constraint django_celery_beat_periodictask_total_run_count_check
            check (total_run_count >= 0),
    date_changed    timestamp with time zone not null,
    description     text                     not null,
    crontab_id      integer
        constraint django_celery_beat_p_crontab_id_d3cba168_fk_django_ce
            references django_celery_beat_crontabschedule
            deferrable initially deferred,
    interval_id     integer
        constraint django_celery_beat_p_interval_id_a8ca27da_fk_django_ce
            references django_celery_beat_intervalschedule
            deferrable initially deferred,
    solar_id        integer
        constraint django_celery_beat_p_solar_id_a87ce72c_fk_django_ce
            references django_celery_beat_solarschedule
            deferrable initially deferred,
    one_off         boolean                  not null,
    start_time      timestamp with time zone,
    priority        integer
        constraint django_celery_beat_periodictask_priority_check
            check (priority >= 0),
    headers         text                     not null,
    clocked_id      integer
        constraint django_celery_beat_p_clocked_id_47a69f82_fk_django_ce
            references django_celery_beat_clockedschedule
            deferrable initially deferred,
    expire_seconds  integer
        constraint django_celery_beat_periodictask_expire_seconds_check
            check (expire_seconds >= 0)
);

alter table django_celery_beat_periodictask
    owner to myscale_kb_backend;

create index django_celery_beat_periodictask_clocked_id_47a69f82
    on django_celery_beat_periodictask (clocked_id);

create index django_celery_beat_periodictask_crontab_id_d3cba168
    on django_celery_beat_periodictask (crontab_id);

create index django_celery_beat_periodictask_interval_id_a8ca27da
    on django_celery_beat_periodictask (interval_id);

create index django_celery_beat_periodictask_name_265a36b7_like
    on django_celery_beat_periodictask (name varchar_pattern_ops);

create index django_celery_beat_periodictask_solar_id_a87ce72c
    on django_celery_beat_periodictask (solar_id);

