create table django_admin_log
(
    id              integer generated by default as identity
        primary key,
    action_time     timestamp with time zone not null,
    object_id       text,
    object_repr     varchar(200)             not null,
    action_flag     smallint                 not null
        constraint django_admin_log_action_flag_check
            check (action_flag >= 0),
    change_message  text                     not null,
    content_type_id integer
        constraint django_admin_log_content_type_id_c4bce8eb_fk_django_co
            references django_content_type
            deferrable initially deferred,
    user_id         varchar(36)              not null
        constraint django_admin_log_user_id_c564eba6_fk_my_user_id
            references my_user
            deferrable initially deferred
);

alter table django_admin_log
    owner to myscale_kb_backend;

create index django_admin_log_content_type_id_c4bce8eb
    on django_admin_log (content_type_id);

create index django_admin_log_user_id_c564eba6
    on django_admin_log (user_id);

create index django_admin_log_user_id_c564eba6_like
    on django_admin_log (user_id varchar_pattern_ops);

