create table django_celery_beat_solarschedule
(
    id        integer generated by default as identity
        primary key,
    event     varchar(24)   not null,
    latitude  numeric(9, 6) not null,
    longitude numeric(9, 6) not null,
    constraint django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq
        unique (event, latitude, longitude)
);

alter table django_celery_beat_solarschedule
    owner to myscale_kb_backend;

