create table email_verification_code
(
    id         bigint generated by default as identity
        primary key,
    email      varchar(254)             not null
        unique,
    code       varchar(6)               not null,
    created_at timestamp with time zone not null,
    is_used    boolean                  not null
);

alter table email_verification_code
    owner to myscale_kb_backend;

create index email_verif_created_7e2ab0_idx
    on email_verification_code (created_at);

create index email_verif_email_ddf238_idx
    on email_verification_code (email);

create index email_verification_code_email_22469c03_like
    on email_verification_code (email varchar_pattern_ops);

