create table global_config
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(256) default NULL::character varying,
    config_type varchar(128) default NULL::character varying,
    sub_type    varchar(128) default NULL::character varying,
    value       jsonb        default 'null'::jsonb,
    "order"     integer      default 0     not null,
    updated_by  varchar(36)  default NULL::character varying,
    updated_at  timestamp with time zone,
    created_at  timestamp with time zone,
    del_flag    boolean      default false not null,
    constraint global_config_config_type_sub_type_6d873e48_uniq
        unique (config_type, sub_type)
);

alter table global_config
    owner to myscale_kb_backend;

