create table invite_code
(
    id            integer generated by default as identity
        primary key,
    code          varchar(32)              not null
        unique,
    description   varchar(255),
    is_active     boolean                  not null,
    max_uses      integer                  not null,
    used_count    integer                  not null,
    created_at    timestamp with time zone not null,
    updated_at    timestamp with time zone not null,
    expires_at    timestamp with time zone,
    created_by_id varchar(36)
        constraint invite_code_created_by_id_b94bccd8_fk_my_user_id
            references my_user
            deferrable initially deferred
);

alter table invite_code
    owner to myscale_kb_backend;

create index invite_code_code_074cf0b0_like
    on invite_code (code varchar_pattern_ops);

create index invite_code_created_by_id_b94bccd8
    on invite_code (created_by_id);

create index invite_code_created_by_id_b94bccd8_like
    on invite_code (created_by_id varchar_pattern_ops);

INSERT INTO public.invite_code (code, description, is_active, max_uses, used_count, created_at, updated_at, expires_at, created_by_id) VALUES ('DCAI2025', '测试邀请码', true, 10000, 7, '2025-11-13 07:39:45.115622 +00:00', '2025-11-28 02:57:28.938382 +00:00', '2029-12-31 23:59:59.000000 +00:00', '697b0938-8e6f-48a3-8f9e-4d082697c331');
