create table my_user_user_permissions
(
    id            integer generated by default as identity
        primary key,
    myuser_id     varchar(36) not null
        constraint my_user_user_permissions_myuser_id_15622681_fk_my_user_id
            references my_user
            deferrable initially deferred,
    permission_id integer     not null
        constraint my_user_user_permiss_permission_id_029e0b67_fk_auth_perm
            references auth_permission
            deferrable initially deferred,
    constraint my_user_user_permissions_myuser_id_permission_id_5223f64f_uniq
        unique (myuser_id, permission_id)
);

alter table my_user_user_permissions
    owner to myscale_kb_backend;

create index my_user_user_permissions_myuser_id_15622681
    on my_user_user_permissions (myuser_id);

create index my_user_user_permissions_myuser_id_15622681_like
    on my_user_user_permissions (myuser_id varchar_pattern_ops);

create index my_user_user_permissions_permission_id_029e0b67
    on my_user_user_permissions (permission_id);

