create table my_user_groups
(
    id        integer generated by default as identity
        primary key,
    myuser_id varchar(36) not null
        constraint my_user_groups_myuser_id_c95fd13e_fk_my_user_id
            references my_user
            deferrable initially deferred,
    group_id  integer     not null
        constraint my_user_groups_group_id_1e2928ac_fk_auth_group_id
            references auth_group
            deferrable initially deferred,
    constraint my_user_groups_myuser_id_group_id_013b43af_uniq
        unique (myuser_id, group_id)
);

alter table my_user_groups
    owner to myscale_kb_backend;

create index my_user_groups_group_id_1e2928ac
    on my_user_groups (group_id);

create index my_user_groups_myuser_id_c95fd13e
    on my_user_groups (myuser_id);

create index my_user_groups_myuser_id_c95fd13e_like
    on my_user_groups (myuser_id varchar_pattern_ops);

