create table openapi_key
(
    id           bigint generated by default as identity
        primary key,
    title        varchar(256)             not null,
    api_key      varchar(128)             not null
        unique,
    api_key_show varchar(128)             not null,
    del_flag     boolean default false    not null,
    updated_at   timestamp with time zone,
    created_at   timestamp with time zone not null,
    user_id      varchar(36),
    last_used_at timestamp with time zone,
    api_key_hash varchar(32)
);

alter table openapi_key
    owner to myscale_kb_backend;

create index openapi_key_api_key_7fa928fd_like
    on openapi_key (api_key varchar_pattern_ops);

create index openapi_key_api_key_hash_d2d06a80
    on openapi_key (api_key_hash);

create index openapi_key_api_key_hash_d2d06a80_like
    on openapi_key (api_key_hash varchar_pattern_ops);

create index openapi_key_user_id_973e139e
    on openapi_key (user_id);

create index openapi_key_user_id_973e139e_like
    on openapi_key (user_id varchar_pattern_ops);

INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$9b7e3ee67550b0555299ccd048e3e586$93083dfbadfe1830c7a6a5dfdaac1a4ee401363c81296e7bfaebbfe313ee96f5', 'sk_0****cd61', false, '2025-08-14 13:04:36.059874 +00:00', '2025-08-14 13:04:36.052603 +00:00', 'b855299f-6c5e-47df-a9fa-513618fa9b95', null, null);
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$55249cd2fa04097dbd40ef0880dbdac2$a8a11e150e2ee8422cdf8cea05d6c2c3b845c896884242d3ea653778a5a860f2', 'sk_0****16e0', false, '2025-08-14 13:04:50.080302 +00:00', '2025-08-14 13:04:50.076133 +00:00', '66aeb461-e026-4123-b41b-24ea61a5a7e3', null, null);
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$1593e1056d2fead3104074745d3bfbe7$a6930f3dd25c1295955c9c8fe9247550b5d8cf79899f7c2bf83f8e354cffcbd5', 'sk_0****76cb', false, '2025-08-14 13:04:52.632556 +00:00', '2025-08-14 13:04:52.628610 +00:00', '87a4e0d5-65db-4163-984b-250c322663ea', null, null);
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$0f184e480787a7308ef082fa8e5c35d9$996fc5cc74714ca4da7386c2fb36e957db7cb8bf8b6a8d83c1201a52aa13a6a6', 'sk-V****d28c', false, '2025-08-14 13:11:51.192601 +00:00', '2025-08-14 13:11:51.187543 +00:00', 'd5af06b1-93e7-480a-8e27-33ee9f13a8d2', null, null);
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$820e07ef544d9f729def3dc820cb9fa3$e016854b20270e4afe8113ad696230876fe873d1ca02f61169104d250839d466', 'sk-y****cec5', false, '2025-08-14 13:25:42.058250 +00:00', '2025-08-14 13:25:42.053266 +00:00', '53b95ef3-49dd-427f-ad6b-59b89b2ca955', null, '4e6ffbd5a0f8bc27c0af88f578bc95a3');
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$b227d25ba642631b0bde89ebc2afb2ab$e6828104ef277a6877f968522bcf2861f6a5c8033f3b5bbd15d8655561620112', 'sk-n****4cc3', false, '2025-09-02 09:29:45.027876 +00:00', '2025-08-14 13:25:45.552338 +00:00', '649dac8d-d2ad-401a-82df-9094c1f6b25f', '2025-09-02 09:29:45.026629 +00:00', 'd03d4d48c4a71cad937cd3f93f2cc7c7');
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('测试key', 'sha256$75027a6579513aabf9f638c0e56c9699$4358ce449fce68c7af048fae1d9e9613d11609cc141e88bf46273a804dd5da75', 'sk-X****19bc', false, '2025-11-25 02:43:05.997625 +00:00', '2025-11-25 02:43:05.982636 +00:00', 'e11baf24-e4e6-4740-8687-ff4d67b5bb52', null, '8b50053e97ed607de6a9c6bcfe1663a8');
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('测试key', 'sha256$73263087c4ee1d1f5c4470217852d068$8c05e85861d2fa398040ffb5537eaf2d578e9445040c41f26ec3f17774fd86dd', 'sk-Q****bb64', false, '2025-11-25 02:43:11.422323 +00:00', '2025-11-25 02:43:11.415039 +00:00', 'dcfacaec-fd5f-4a49-b2c3-40c8fb57a678', null, 'a6f1e22f94d7ee6292ea63f2d2f2dc4a');
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('测试key', 'sha256$4caf0159634de6735bb00ec8fcbed1fb$adc08ec3d671b86d141dad0a23a7fdbeff0002ed1c868ab8197b5d88557ecff5', 'sk-O****5314', false, '2025-11-25 06:21:30.481725 +00:00', '2025-11-25 06:21:30.474586 +00:00', '5c54bd4d-fba7-4e1a-88ab-e14b777ae9bc', null, 'c99c4429fd95e1eea6f3fccfbfa98f04');
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('我的API Key', 'sha256$0e22727ff1dc5d5fe521bdc665300409$3d4cbf04613e28415ae5b8ed0f81d2d9b8cf22737051abcdc316644d084d3744', 'sk-t****77d2', false, '2026-03-09 10:00:01.694218 +00:00', '2025-08-14 16:44:51.564533 +00:00', 'fdc68f16-3bd1-4d83-81c1-edd293749d10', '2026-03-09 10:00:01.694122 +00:00', '8fe6347720cf4a3ffac07c219f392b2c');
INSERT INTO public.openapi_key (title, api_key, api_key_show, del_flag, updated_at, created_at, user_id, last_used_at, api_key_hash) VALUES ('测试key', 'sha256$693db9ee66837ffb93d5ec3b3b46a95b$00b4119af53037c9312290b911b2548346891b3aeb7c05d4c38e7cc02f1f572d', 'sk-F****dbe0', false, '2025-12-01 07:22:06.372963 +00:00', '2025-11-25 02:43:28.984647 +00:00', 'ad41f79f-1890-49b7-952a-5b39979ababb', '2025-12-01 07:22:06.372764 +00:00', '8b9e2b68ea82376fb2070d6c33860687');
