create table openapi_log
(
    id             bigint generated by default as identity
        primary key,
    model          varchar(256) default NULL::character varying,
    api            integer                  not null,
    obj_id1        varchar(40)  default NULL::character varying,
    obj_id2        varchar(40)  default NULL::character varying,
    obj_id3        bigint,
    status         integer      default 0   not null,
    updated_at     timestamp with time zone,
    created_at     timestamp with time zone not null,
    openapi_key_id bigint,
    user_id        varchar(36)
);

alter table openapi_log
    owner to myscale_kb_backend;

create index openapi_log_api_de8b7291
    on openapi_log (api);

create index openapi_log_created_at_fcf2b294
    on openapi_log (created_at);

create index openapi_log_obj_id1_a7f0d2b8
    on openapi_log (obj_id1);

create index openapi_log_obj_id1_a7f0d2b8_like
    on openapi_log (obj_id1 varchar_pattern_ops);

create index openapi_log_obj_id2_d756de21
    on openapi_log (obj_id2);

create index openapi_log_obj_id2_d756de21_like
    on openapi_log (obj_id2 varchar_pattern_ops);

create index openapi_log_obj_id3_c89e7e7e
    on openapi_log (obj_id3);

create index openapi_log_openapi_key_id_17059dee
    on openapi_log (openapi_key_id);

create index openapi_log_user_id_883d50f3
    on openapi_log (user_id);

create index openapi_log_user_id_883d50f3_like
    on openapi_log (user_id varchar_pattern_ops);

