create table openapi_usage
(
    id             bigint generated by default as identity
        primary key,
    model          varchar(256) default ''::character varying not null,
    api            integer                                    not null,
    date           date                                       not null,
    total          bigint                                     not null,
    updated_at     timestamp with time zone,
    created_at     timestamp with time zone                   not null,
    openapi_key_id bigint,
    user_id        varchar(36),
    constraint openapi_usage_user_id_openapi_key_id_m_70131370_uniq
        unique (user_id, openapi_key_id, model, api, date)
);

alter table openapi_usage
    owner to myscale_kb_backend;

create index openapi_usage_api_2da04e1a
    on openapi_usage (api);

create index openapi_usage_created_at_eed12979
    on openapi_usage (created_at);

create index openapi_usage_date_c4fd5b4d
    on openapi_usage (date);

create index openapi_usage_openapi_key_id_8a249782
    on openapi_usage (openapi_key_id);

create index openapi_usage_user_id_ebba1ae8
    on openapi_usage (user_id);

create index openapi_usage_user_id_ebba1ae8_like
    on openapi_usage (user_id varchar_pattern_ops);

