create table template
(
    id                integer generated by default as identity
        primary key,
    name              varchar(255)             not null,
    description       text,
    pipeline_config   jsonb                    not null,
    tags              jsonb                    not null,
    detail            jsonb                    not null,
    user_id           varchar(255)             not null,
    del_flag          boolean                  not null,
    created_at        timestamp with time zone not null,
    updated_at        timestamp with time zone not null,
    template_type     varchar(50)              not null,
    link              text,
    pipeline_config_a jsonb                    not null,
    pipeline_config_v jsonb                    not null
);

alter table template
    owner to myscale_kb_backend;

create index idx_template_name
    on template (name);

create index idx_template_user_id
    on template (user_id);
