# Generated by Django 4.2.28 on 2026-03-10 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAPIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('key_hash', models.CharField(blank=True, default='', max_length=128)),
                ('key_type', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read & Write'), ('admin', 'Admin')], default='read', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('rate_limit', models.IntegerField(default=100, help_text='Requests per minute')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openapi_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OpenAPI Key',
                'verbose_name_plural': 'OpenAPI Keys',
                'db_table': 'openapi_key',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpenAPIAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query_params', models.JSONField(blank=True, default=dict)),
                ('request_body', models.TextField(blank=True, default='')),
                ('response_status', models.IntegerField()),
                ('response_time', models.IntegerField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='openapi.openapikey')),
            ],
            options={
                'verbose_name': 'OpenAPI Access Log',
                'verbose_name_plural': 'OpenAPI Access Logs',
                'db_table': 'openapi_access_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='openapi_acc_created_97bf94_idx'), models.Index(fields=['api_key', '-created_at'], name='openapi_acc_api_key_4f638a_idx')],
            },
        ),
    ]
